language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install 'flake8<3.8'
  - pip install python-multipart requests
  - pip install jinja2 pyyaml starlette uvicorn
  - pip install .
script:
  - python -m unittest discover
  - flake8 .
